In [1]:
import hereutil
hereutil.add_to_sys_path(hereutil.here())
from src.common_basis_gizmosql import *

  0%|          | 0/72 [00:00<?, ?it/s]

In [4]:
bnf.head(5).collect(backend='polars').to_native()

shape: (5, 6)
┌───────────────┬──────────────┬─────────────────┬────────────┬───────────────┬────────────────────┐
│ record_number ┆ field_number ┆ subfield_number ┆ field_code ┆ subfield_code ┆ value              │
│ ---           ┆ ---          ┆ ---             ┆ ---        ┆ ---           ┆ ---                │
│ i32           ┆ i32          ┆ i32             ┆ str        ┆ str           ┆ str                │
╞═══════════════╪══════════════╪═════════════════╪════════════╪═══════════════╪════════════════════╡
│ 38            ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 493           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 656           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 861           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 1009          ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
└───────────────┴──────────────┴─────────────────┴────────────┴───────────────┴────────────────────┘

In [1]:
import hereutil
hereutil.add_to_sys_path(hereutil.here())
from src.common_basis_quack import *

  0%|          | 0/71 [00:00<?, ?it/s]

In [3]:
bnf.head(5).collect(backend='polars').to_native()

shape: (5, 6)
┌───────────────┬──────────────┬─────────────────┬────────────┬───────────────┬────────────────────┐
│ record_number ┆ field_number ┆ subfield_number ┆ field_code ┆ subfield_code ┆ value              │
│ ---           ┆ ---          ┆ ---             ┆ ---        ┆ ---           ┆ ---                │
│ i32           ┆ i32          ┆ i32             ┆ str        ┆ str           ┆ str                │
╞═══════════════╪══════════════╪═════════════════╪════════════╪═══════════════╪════════════════════╡
│ 4094440       ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 4094603       ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 4094608       ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 4094611       ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45e │
│ 4094688       ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45e │
└───────────────┴──────────────┴─────────────────┴────────────┴───────────────┴────────────────────┘

In [1]:
import hereutil
hereutil.add_to_sys_path(hereutil.here())
from src.common_basis_s3 import *

  0%|          | 0/72 [00:00<?, ?it/s]

In [5]:
bnf.head(5).collect(backend='polars').to_native()

shape: (5, 6)
┌───────────────┬──────────────┬─────────────────┬────────────┬───────────────┬────────────────────┐
│ record_number ┆ field_number ┆ subfield_number ┆ field_code ┆ subfield_code ┆ value              │
│ ---           ┆ ---          ┆ ---             ┆ ---        ┆ ---           ┆ ---                │
│ i32           ┆ i32          ┆ i32             ┆ str        ┆ str           ┆ str                │
╞═══════════════╪══════════════╪═════════════════╪════════════╪═══════════════╪════════════════════╡
│ 38            ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 493           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 656           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 861           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 1009          ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
└───────────────┴──────────────┴─────────────────┴────────────┴───────────────┴────────────────────┘

In [2]:
import hereutil
hereutil.add_to_sys_path(hereutil.here())
from src.common_basis_local import *

  0%|          | 0/74 [00:00<?, ?it/s]

In [3]:
bnf.head(5).collect(backend='polars').to_native()

shape: (5, 6)
┌───────────────┬──────────────┬─────────────────┬────────────┬───────────────┬────────────────────┐
│ record_number ┆ field_number ┆ subfield_number ┆ field_code ┆ subfield_code ┆ value              │
│ ---           ┆ ---          ┆ ---             ┆ ---        ┆ ---           ┆ ---                │
│ i32           ┆ i32          ┆ i32             ┆ str        ┆ str           ┆ str                │
╞═══════════════╪══════════════╪═════════════════╪════════════╪═══════════════╪════════════════════╡
│ 38            ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 493           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 656           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 861           ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
│ 1009          ┆ 2            ┆ 1               ┆ 000        ┆               ┆ n0 d922        45a │
└───────────────┴──────────────┴─────────────────┴────────────┴───────────────┴────────────────────┘